controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media